on:
  schedule:
    - cron:  "0 6 * * *"
  workflow_dispatch:

name: Script_R_ONDE_Normandie

jobs:
  run-r-script:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::devtools
            
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1' # Pandoc version pour compiler.
          
      - name: Installation packages in dev
        run: Rscript -e 'devtools::install_github("richaben/ondetools")'
        
      - name: Install dependencies
        run: |
          install.packages(c("hubeau", "leaflet", "leaflet.extras","ggrepel", "scales", "data.table"))
        shell: Rscript {0}
        
      - name: Execute Scripts Telechargement et Mise en forme
        run: |
          Rscript "01_telechargement_data.R"
          
      - name: Commit Results 
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script $(date)" || echo "No changes to commit"
          git push origin -f || echo "No changes to commit"-
          
      - name: Render rapport
        run: |
          R -e 'Sys.setlocale("LC_TIME", "fr_FR")'
          Rscript "02_generer_rapport_html.R"
          
      - name: Deploy Pages 
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html
          git commit -m "Render Rmarkdown $(date)" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-    
