on:
  schedule:
    - cron:  "30 0 * * *"
  workflow_dispatch:

name: Script_R_ONDE_Normandie

jobs:
  run-r-script:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::devtools
        
      - name: Installation packages in dev
        run: Rscript -e 'devtools::install_github("richaben/ondetools")'
        
      - name: Install dependencies
        run: |
          install.packages(c("hubeau", "leaflet", "leaflet.extras"))
        shell: Rscript {0}
        
      - name: Execute Scripts
        run: |
          Rscript "01_telechargement_data.R"
      - name: Commit Results and Deploy Pages 
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-
